import { expect, test } from 'vitest'

import {
  FA_VERTICAL_DRAGGABLE_TABS_COLUMN_WIDTH_PX_DEFAULT,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_COLUMN_WIDTH,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_JUSTIFY_CONTENT,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_FONT_SIZE,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_TEXT_TRANSFORM,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_MIN_HEIGHT,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_PADDING,
  FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_TEXT_ALIGN,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_JUSTIFY_CONTENT_DEFAULT,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_FONT_SIZE_DEFAULT,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_TEXT_TRANSFORM_DEFAULT,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_MIN_HEIGHT_DENSE_PX,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_PADDING_DEFAULT,
  FA_VERTICAL_DRAGGABLE_TABS_TAB_TEXT_ALIGN_DEFAULT,
  buildFaVerticalDraggableTabsRootStyle
} from '../functions/buildFaVerticalDraggableTabsRootStyle'

/**
 * buildFaVerticalDraggableTabsRootStyle
 * Maps tab list props to CSS custom properties on the column root.
 */
test('Test that buildFaVerticalDraggableTabsRootStyle applies default tab chrome values', () => {
  expect(buildFaVerticalDraggableTabsRootStyle({
    columnWidthPx: FA_VERTICAL_DRAGGABLE_TABS_COLUMN_WIDTH_PX_DEFAULT,
    tabJustifyContent: FA_VERTICAL_DRAGGABLE_TABS_TAB_JUSTIFY_CONTENT_DEFAULT,
    tabLabelFontSize: FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_FONT_SIZE_DEFAULT,
    tabLabelTextTransform: FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_TEXT_TRANSFORM_DEFAULT,
    tabPadding: FA_VERTICAL_DRAGGABLE_TABS_TAB_PADDING_DEFAULT,
    tabTextAlign: FA_VERTICAL_DRAGGABLE_TABS_TAB_TEXT_ALIGN_DEFAULT
  })).toEqual({
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_COLUMN_WIDTH]: '240px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_JUSTIFY_CONTENT]: 'flex-start',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_FONT_SIZE]: '15px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_TEXT_TRANSFORM]: 'none',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_PADDING]: '4px 40px 4px 60px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_TEXT_ALIGN]: 'left'
  })
})

/**
 * buildFaVerticalDraggableTabsRootStyle
 * Accepts custom tab chrome overrides for Project Settings hosts.
 */
test('Test that buildFaVerticalDraggableTabsRootStyle forwards custom tab chrome props', () => {
  expect(buildFaVerticalDraggableTabsRootStyle({
    columnWidthPx: 360,
    tabJustifyContent: 'center',
    tabLabelFontSize: '18px',
    tabLabelTextTransform: 'uppercase',
    tabPadding: '8px 12px',
    tabTextAlign: 'right'
  })).toEqual({
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_COLUMN_WIDTH]: '360px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_JUSTIFY_CONTENT]: 'center',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_FONT_SIZE]: '18px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_TEXT_TRANSFORM]: 'uppercase',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_PADDING]: '8px 12px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_TEXT_ALIGN]: 'right'
  })
})

/**
 * buildFaVerticalDraggableTabsRootStyle
 * Dense mode lowers tab row min-height to 36px.
 */
test('Test that buildFaVerticalDraggableTabsRootStyle applies dense tab min-height', () => {
  expect(buildFaVerticalDraggableTabsRootStyle({
    columnWidthPx: FA_VERTICAL_DRAGGABLE_TABS_COLUMN_WIDTH_PX_DEFAULT,
    tabDense: true,
    tabJustifyContent: FA_VERTICAL_DRAGGABLE_TABS_TAB_JUSTIFY_CONTENT_DEFAULT,
    tabLabelFontSize: FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_FONT_SIZE_DEFAULT,
    tabLabelTextTransform: FA_VERTICAL_DRAGGABLE_TABS_TAB_LABEL_TEXT_TRANSFORM_DEFAULT,
    tabPadding: FA_VERTICAL_DRAGGABLE_TABS_TAB_PADDING_DEFAULT,
    tabTextAlign: FA_VERTICAL_DRAGGABLE_TABS_TAB_TEXT_ALIGN_DEFAULT
  })).toEqual({
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_COLUMN_WIDTH]: '240px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_JUSTIFY_CONTENT]: 'flex-start',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_FONT_SIZE]: '15px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_LABEL_TEXT_TRANSFORM]: 'none',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_MIN_HEIGHT]: `${FA_VERTICAL_DRAGGABLE_TABS_TAB_MIN_HEIGHT_DENSE_PX}px`,
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_PADDING]: '4px 40px 4px 60px',
    [FA_VERTICAL_DRAGGABLE_TABS_CSS_VAR_TAB_TEXT_ALIGN]: 'left'
  })
})
