import type { I_faUserSettings } from 'app/types/I_faUserSettingsDomain'

export const FA_USER_SETTINGS_DEFAULTS: I_faUserSettings = {
  aggressiveRelationshipFilter: false,
  allowQuickPopupSameKeyClose: false,
  allowWiderScrollbars: false,
  compactDocumentCount: false,
  compactTags: false,
  darkMode: false,
  disableCloseAfterSelectQuickSearch: false,
  disableDocumentControlBar: false,
  disableDocumentControlBarGuides: false,
  disableDocumentCounts: false,
  disableDocumentToolTips: false,
  disableQuickSearchCategoryPrecheck: false,
  disableSpellCheck: false,
  doNotCollapseTreeOptions: false,
  doubleDashDocCount: false,
  hideAdvSearchCheatsheetButton: false,
  hideDeadCrossThrough: false,
  hideDocumentTitles: false,
  hideEmptyFields: false,
  hideHierarchyTree: false,
  hidePlushes: false,
  hideTooltipsProject: false,
  hideTooltipsStart: false,
  hideTreeExtraIcons: false,
  hideTreeIconAddUnder: false,
  hideTreeIconEdit: false,
  hideTreeIconView: false,
  hideTreeOrderNumbers: false,
  hideWelcomeScreenSocials: false,
  invertCategoryPosition: false,
  invertTreeSorting: false,
  languageCode: 'en-US',
  limitEditorHeight: false,
  noProjectName: false,
  noTags: false,
  preventAutoScroll: false,
  preventFilledNoteBoardPopup: false,
  preventPreviewsDocuments: false,
  preventPreviewsPopups: false,
  preventPreviewsTabs: true,
  preventPreviewsTree: true,
  showDocumentID: false,
  tagsAtTop: false,
  textShadow: false
}
